spring.application.name=analytics-service

# Database Configuration
spring.datasource.url=${DB_URL_ANALYTICS}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port (Mapped via Docker Compose)
server.port=${SERVER_PORT:8084}

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ANALYTICS:fraudly-analytics-service}
spring.kafka.consumer.auto-offset-reset=${KAFKA_AUTO_OFFSET_RESET:earliest}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka Topics
kafka.topic.tutor.interaction=${KAFKA_TOPIC_TUTOR_INTERACTION:tutor.interaction_logged}
kafka.topic.student.progress=${KAFKA_TOPIC_STUDENT_PROGRESS:student.progress_updated}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_ZONE:http://discovery-service:8761/eureka/}
eureka.instance.prefer-ip-address=true
