spring.application.name=analytics-service

# Database Configuration (Using service name: pgdb)
spring.datasource.url=${DB_URL_ANALYTICS}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=${SERVER_PORT_ANALYTICS}

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ANALYTICS}
spring.kafka.consumer.auto-offset-reset=${KAFKA_AUTO_OFFSET_RESET}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka Topics
kafka.topic.tutor.interaction=${KAFKA_TOPIC_TUTOR_INTERACTION}
kafka.topic.student.progress=${KAFKA_TOPIC_STUDENT_PROGRESS}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

springdoc.data-rest.enabled=false

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_ZONE}
eureka.instance.prefer-ip-address=true