spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # THIS IS MANDATORY for dynamic routing
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://authentification-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: learning-service
          uri: lb://learning-service
          predicates:
            - Path=/api/learning/**,/api/enrolements/**,/api/courses/**,/api/resources/**,/api/tutor/**
          filters:
            - StripPrefix=0
        - id: assessment-service
          uri: lb://assessment-service
          predicates:
            - Path=/api/exams/**
          filters:
            - StripPrefix=0
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**a
          filters:
            - StripPrefix=0
        - id: proctoring-service
          uri: lb://proctoring-service
          predicates:
            - Path=/api/collusion/**,/api/proctoring/**
          filters:
            - StripPrefix=0

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE:http://discovery-service:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,mappings,env,gateway"
  endpoint:
    gateway:
      enabled: true