spring.application.name=learning-service
server.port=8082
spring.datasource.url=jdbc:h2:mem:lerning-db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=false


# AWS Credentials (à mettre à jour à chaque session !)
aws.accessKey=ASIAX3GE6DTVM273J5ZZ
aws.secretKey=M5C0SF+QvKIxZO20be73OOCAxzmJCmArFNAITsac
aws.sessionToken=IQoJb3JpZ2luX2VjEND//////////wEaCXVzLXdlc3QtMiJGMEQCIF5rMHzVQYmtANnmdPNeq71uSCKM1f3RpFmEbp6U2yzuAiBaTFyUaTk7WtKrbH5/WeolVDseGOBJBCUKlOecDaHpliq9AgiZ//////////8BEAEaDDUzOTQzMTQxMDkyMiIMfl0vM/sqBLK8tNz7KpECRlZM8IOf+h4ckC65A3k704oMsEqyaxnJ4H8hYyYi7JxcXtPd5aRQSeQi2sgvhbQN9Ux/QW3WQ6RQTOkyy7QqB3TQXAH41750J92HtYgcetDp/72Z17NA7qBsBvcVmnizf7n6X0hDgmrsgoUol3QizhoNfm3pkWJsxKcHPr3Ehk9Vi+9vFIgP+ttJyIUR9AGVKkMJYrU4Y0YJawGTi3zi28AuMh4x/MvyjJ/+sr4yFLRk96RQf2YBgHv/ty9xDLwCulAeelvsfy+onxepYcdRsIV/BdhZFufu/fnIwEtz5vom09VhAyuvmLzKh32YkHhfp8SKhTMFCnZH+AQtcgBKGW4gSM4VAdBh9bhOqD6mZCjrMIPt688GOp4BU1xto2KTNFdwwEkOzOC5kAnfVVVdg7UVTPkfQN5sfvj5DErv/1kAVz3BDEkphVEXSIcGpPlL5YOxdbjLTtC8W6mnIi/ezyjMyeD4MkJtX+15KJJOe342M5wE2bKMHn5hxpSfiv8nk+ONR5rNlcDrPlrdBcm4sUtId8oMBLgIlh6xUmS/iHvvxVBk/ODqfz7COITp5z0OfYpncX/71u8=
aws.region=us-east-1
aws.bucketName=test-s3-lerning
