spring.application.name=authentification-service

# PostgreSQL (use docker service-name defaults)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fraudly_auth}
spring.datasource.username=${DB_USER:fraudly}
spring.datasource.password=${DB_PASSWORD:fraudly}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_SECRET:ZnJhdWRseS1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tMjAyNQ==}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# Server port (overridable via env)
server.port=${SERVER_PORT:8081}