spring.application.name=authentification-service

# 1. On importe les secrets depuis AWS Secrets Manager
spring.config.import=aws-secretsmanager:fraudly/auth-service

# 2. Base de données (Sécurisée)
spring.datasource.url=${DB_URL:jdbc:postgresql://pgdb:5432/fraudly_auth}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Sécurité JWT (Sécurisée)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# Serveur
server.port=${SERVER_PORT:8081}