spring.application.name=proctoring-service
# Database URL (in memory by default)
spring.datasource.url=${DB_URL_proctoring:jdbc:h2:mem:testdb}
spring.datasource.driverClassName=${DB_DRIVER_proctoring:org.h2.Driver}
spring.datasource.username=${DB_USER_proctoring:sa}
spring.datasource.password=${DB_PASSWORD_proctoring:}
spring.jpa.database-platform=${DB_DIALECT_proctoring:org.hibernate.dialect.H2Dialect}
# Enable H2 console
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
#newortk h2
spring.h2.console.settings.web-allow-others=true

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:fraudly-proctoring-service}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka Topics
kafka.topic.collusion.suspected=${KAFKA_TOPIC_COLLUSION_SUSPECTED:proctor.collusion_suspected}
