spring.application.name=proctoring-service
spring.config.import=optional:file:.env[.properties]

# Database Configuration
spring.datasource.url=${DB_URL_PROCTORING}
spring.datasource.username=${DB_USER_PROCTORING}
spring.datasource.password=${DB_PASSWORD_PROCTORING}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=${SERVER_PORT_PROCTORING}

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=${KAFKA_AUTO_OFFSET_RESET}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka Topics
kafka.topic.collusion.suspected=${KAFKA_TOPIC_COLLUSION_SUSPECTED}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

springdoc.data-rest.enabled=false

# Eureka Discovery
eureka.client.service-url.defaultZone=${EUREKA_ZONE}
eureka.instance.prefer-ip-address=true