spring.application.name=discavery-service
server.port=8761

# Eureka Server (il ne s?enregistre pas lui-même)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Option Docker
eureka.instance.hostname=discavery-service